apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    app: web-server
    tier: web
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx